# Generated by Django 5.0.7 on 2024-09-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busketproducts',
            name='busket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='busket.busket'),
        ),
    ]
