# Generated by Django 5.0.7 on 2024-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('anons', models.CharField(max_length=255, verbose_name='anons')),
                ('full_story', models.TextField(verbose_name='full_story')),
                ('datetime', models.DateField(verbose_name='datetime')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
